import { GitHubBanner } from "@refinedev/core";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import "@refinedev/antd/dist/reset.css";
import { RefineContext } from "./_refine_context";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  // call api me
  const me = {
    permission: "admin",
  };

  return (
    <html lang="en">
      <body>
        <Suspense>
          <GitHubBanner />
          <RefineContext defaultMode={defaultMode} meData={me}>
            {children}
          </RefineContext>
        </Suspense>
      </body>
    </html>
  );
}
