// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  Ac9C4D978Ea4E5B72915Ca9728E5B8B1Data,
  Ac9C4D978Ea4E5B72915Ca9728E5B8B1Responses,
  B5Adb0520Cca80Cedfe09D9298332Data,
  B5Adb0520Cca80Cedfe09D9298332Errors,
  B5Adb0520Cca80Cedfe09D9298332Responses,
  B61B65823F4A21F182506B34Ddf805cData,
  B61B65823F4A21F182506B34Ddf805cErrors,
  B61B65823F4A21F182506B34Ddf805cResponses,
  Bb2E47Dde77Dd1E2591428B0Ae1Data,
  Bb2E47Dde77Dd1E2591428B0Ae1Errors,
  Bb2E47Dde77Dd1E2591428B0Ae1Responses,
  Cca49A87D9B0Ebb9A98Ad7C154B71737Data,
  Cca49A87D9B0Ebb9A98Ad7C154B71737Errors,
  Cca49A87D9B0Ebb9A98Ad7C154B71737Responses,
  D99F2E42Af2F722A058A86245Aa856fData,
  D99F2E42Af2F722A058A86245Aa856fResponses,
  Dcb66200C3132996151884Ac232Cf439Data,
  Dcb66200C3132996151884Ac232Cf439Responses,
  Dcf71887E585De7F881E9Eb98D86126Data,
  Dcf71887E585De7F881E9Eb98D86126Errors,
  Dcf71887E585De7F881E9Eb98D86126Responses,
  F4Bed0846D9350903D8A17C7B503aData,
  F4Bed0846D9350903D8A17C7B503aResponses,
  Fda362E2E082B5357Ac416E7767E435Data,
  Fda362E2E082B5357Ac416E7767E435Responses,
} from "./types.gen";
import {
  zAc9C4D978Ea4E5B72915Ca9728E5B8B1Data,
  zB5Adb0520Cca80Cedfe09D9298332Data,
  zB61B65823F4A21F182506B34Ddf805cData,
  zBb2E47Dde77Dd1E2591428B0Ae1Data,
  zCca49A87D9B0Ebb9A98Ad7C154B71737Data,
  zD99F2E42Af2F722A058A86245Aa856fData,
  zDcb66200C3132996151884Ac232Cf439Data,
  zDcf71887E585De7F881E9Eb98D86126Data,
  zF4Bed0846D9350903D8A17C7B503aData,
  zFda362E2E082B5357Ac416E7767E435Data,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Lấy danh sách danh mục (có phân trang)
 */
export const ac9C4D978Ea4E5B72915Ca9728E5B8B1 = <
  ThrowOnError extends boolean = false
>(
  options?: Options<Ac9C4D978Ea4E5B72915Ca9728E5B8B1Data, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    Ac9C4D978Ea4E5B72915Ca9728E5B8B1Responses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAc9C4D978Ea4E5B72915Ca9728E5B8B1Data.parseAsync(data);
    },
    url: "/api/categories",
    ...options,
  });
};

/**
 * Tạo danh mục mới
 */
export const cca49A87D9B0Ebb9A98Ad7C154B71737 = <
  ThrowOnError extends boolean = false
>(
  options: Options<Cca49A87D9B0Ebb9A98Ad7C154B71737Data, ThrowOnError>
) => {
  return (options.client ?? client).post<
    Cca49A87D9B0Ebb9A98Ad7C154B71737Responses,
    Cca49A87D9B0Ebb9A98Ad7C154B71737Errors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCca49A87D9B0Ebb9A98Ad7C154B71737Data.parseAsync(data);
    },
    url: "/api/categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Xoá danh mục
 */
export const b61B65823F4A21F182506B34Ddf805C = <
  ThrowOnError extends boolean = false
>(
  options: Options<B61B65823F4A21F182506B34Ddf805cData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    B61B65823F4A21F182506B34Ddf805cResponses,
    B61B65823F4A21F182506B34Ddf805cErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zB61B65823F4A21F182506B34Ddf805cData.parseAsync(data);
    },
    url: "/api/categories/{id}",
    ...options,
  });
};

/**
 * Xem chi tiết danh mục
 */
export const bb2E47Dde77Dd1E2591428B0Ae1 = <
  ThrowOnError extends boolean = false
>(
  options: Options<Bb2E47Dde77Dd1E2591428B0Ae1Data, ThrowOnError>
) => {
  return (options.client ?? client).get<
    Bb2E47Dde77Dd1E2591428B0Ae1Responses,
    Bb2E47Dde77Dd1E2591428B0Ae1Errors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zBb2E47Dde77Dd1E2591428B0Ae1Data.parseAsync(data);
    },
    url: "/api/categories/{id}",
    ...options,
  });
};

/**
 * Cập nhật danh mục
 */
export const dcf71887E585De7F881E9Eb98D86126 = <
  ThrowOnError extends boolean = false
>(
  options: Options<Dcf71887E585De7F881E9Eb98D86126Data, ThrowOnError>
) => {
  return (options.client ?? client).put<
    Dcf71887E585De7F881E9Eb98D86126Responses,
    Dcf71887E585De7F881E9Eb98D86126Errors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDcf71887E585De7F881E9Eb98D86126Data.parseAsync(data);
    },
    url: "/api/categories/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Lấy danh sách bài viết (có phân trang)
 */
export const fda362E2E082B5357Ac416E7767E435 = <
  ThrowOnError extends boolean = false
>(
  options?: Options<Fda362E2E082B5357Ac416E7767E435Data, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    Fda362E2E082B5357Ac416E7767E435Responses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zFda362E2E082B5357Ac416E7767E435Data.parseAsync(data);
    },
    url: "/api/posts",
    ...options,
  });
};

/**
 * Tạo mới bài viết
 */
export const dcb66200C3132996151884Ac232Cf439 = <
  ThrowOnError extends boolean = false
>(
  options: Options<Dcb66200C3132996151884Ac232Cf439Data, ThrowOnError>
) => {
  return (options.client ?? client).post<
    Dcb66200C3132996151884Ac232Cf439Responses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDcb66200C3132996151884Ac232Cf439Data.parseAsync(data);
    },
    url: "/api/posts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Xoá bài viết
 */
export const d99F2E42Af2F722A058A86245Aa856F = <
  ThrowOnError extends boolean = false
>(
  options: Options<D99F2E42Af2F722A058A86245Aa856fData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    D99F2E42Af2F722A058A86245Aa856fResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zD99F2E42Af2F722A058A86245Aa856fData.parseAsync(data);
    },
    url: "/api/posts/{id}",
    ...options,
  });
};

/**
 * Xem chi tiết bài viết
 */
export const b5Adb0520Cca80Cedfe09D9298332 = <
  ThrowOnError extends boolean = false
>(
  options: Options<B5Adb0520Cca80Cedfe09D9298332Data, ThrowOnError>
) => {
  return (options.client ?? client).get<
    B5Adb0520Cca80Cedfe09D9298332Responses,
    B5Adb0520Cca80Cedfe09D9298332Errors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zB5Adb0520Cca80Cedfe09D9298332Data.parseAsync(data);
    },
    url: "/api/posts/{id}",
    ...options,
  });
};

/**
 * Cập nhật bài viết
 */
export const f4Bed0846D9350903D8A17C7B503A = <
  ThrowOnError extends boolean = false
>(
  options: Options<F4Bed0846D9350903D8A17C7B503aData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    F4Bed0846D9350903D8A17C7B503aResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zF4Bed0846D9350903D8A17C7B503aData.parseAsync(data);
    },
    url: "/api/posts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
