// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type CategoryRequest = {
  /**
   * required:Tên danh mục là bắt buộc.|type:Tên danh mục phải là chuỗi .|max: Tên danh mục không vượt quá 255 ký tự.
   */
  title: string;
  description?: string | null;
};

export type PostRequest = {
  /**
   * Tiêu đề bài viết. Bắt buộc, tối đa 255 ký tự.
   */
  title: string;
  /**
   * Nội dung bài viết (không bắt buộc).
   */
  content?: string | null;
  /**
   * ID danh mục mà bài viết thuộc về. Bắt buộc, phải tồn tại trong bảng categories.
   */
  category_id: number;
  /**
   * Danh sách các thẻ (tags) — có thể bỏ trống, mỗi thẻ phải là chuỗi có ít nhất 2 ký tự.
   */
  tags?: Array<string> | null;
};

/**
 * Category
 */
export type Category = {
  id?: number;
  title: string;
  description?: string;
  created_at?: string;
  updated_at?: string;
};

export type Post = {
  id?: number;
  title?: string;
  content?: string | null;
  category_id?: number;
  tags?: Array<string> | null;
  category?: Category;
};

export type PaginationLinks = {
  first?: string;
  last?: string;
  prev?: string | null;
  next?: string | null;
};

export type PaginationMeta = {
  current_page?: number;
  from?: number;
  last_page?: number;
  path?: string;
  per_page?: number;
  to?: number;
  total?: number;
};

export type Ac9C4D978Ea4E5B72915Ca9728E5B8B1Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Số trang (mặc định: 1)
     */
    page?: number;
    /**
     * Số phần tử mỗi trang (mặc định: 15)
     */
    per_page?: number;
  };
  url: "/api/categories";
};

export type Ac9C4D978Ea4E5B72915Ca9728E5B8B1Responses = {
  /**
   * Danh sách danh mục (phân trang)
   */
  200: {
    data?: Array<Category>;
    links?: PaginationLinks;
    meta?: PaginationMeta;
  };
};

export type Ac9C4D978Ea4E5B72915Ca9728E5B8B1Response =
  Ac9C4D978Ea4E5B72915Ca9728E5B8B1Responses[keyof Ac9C4D978Ea4E5B72915Ca9728E5B8B1Responses];

export type Cca49A87D9B0Ebb9A98Ad7C154B71737Data = {
  body: CategoryRequest;
  path?: never;
  query?: never;
  url: "/api/categories";
};

export type Cca49A87D9B0Ebb9A98Ad7C154B71737Errors = {
  /**
   * Lỗi validation
   */
  422: unknown;
};

export type Cca49A87D9B0Ebb9A98Ad7C154B71737Responses = {
  /**
   * Tạo thành công
   */
  201: Category;
};

export type Cca49A87D9B0Ebb9A98Ad7C154B71737Response =
  Cca49A87D9B0Ebb9A98Ad7C154B71737Responses[keyof Cca49A87D9B0Ebb9A98Ad7C154B71737Responses];

export type B61B65823F4A21F182506B34Ddf805cData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/categories/{id}";
};

export type B61B65823F4A21F182506B34Ddf805cErrors = {
  /**
   * Không tìm thấy
   */
  404: unknown;
};

export type B61B65823F4A21F182506B34Ddf805cResponses = {
  /**
   * Xoá thành công
   */
  200: unknown;
};

export type Bb2E47Dde77Dd1E2591428B0Ae1Data = {
  body?: never;
  path: {
    /**
     * ID danh mục
     */
    id: number;
  };
  query?: never;
  url: "/api/categories/{id}";
};

export type Bb2E47Dde77Dd1E2591428B0Ae1Errors = {
  /**
   * Không tìm thấy
   */
  404: unknown;
};

export type Bb2E47Dde77Dd1E2591428B0Ae1Responses = {
  /**
   * Chi tiết danh mục
   */
  200: Category;
};

export type Bb2E47Dde77Dd1E2591428B0Ae1Response =
  Bb2E47Dde77Dd1E2591428B0Ae1Responses[keyof Bb2E47Dde77Dd1E2591428B0Ae1Responses];

export type Dcf71887E585De7F881E9Eb98D86126Data = {
  body: CategoryRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/categories/{id}";
};

export type Dcf71887E585De7F881E9Eb98D86126Errors = {
  /**
   * Lỗi validation
   */
  422: unknown;
};

export type Dcf71887E585De7F881E9Eb98D86126Responses = {
  /**
   * Cập nhật thành công
   */
  200: Category;
};

export type Dcf71887E585De7F881E9Eb98D86126Response =
  Dcf71887E585De7F881E9Eb98D86126Responses[keyof Dcf71887E585De7F881E9Eb98D86126Responses];

export type Fda362E2E082B5357Ac416E7767E435Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Số trang hiện tại (mặc định: 1)
     */
    page?: number;
    /**
     * Số bài viết mỗi trang (mặc định: 15)
     */
    per_page?: number;
  };
  url: "/api/posts";
};

export type Fda362E2E082B5357Ac416E7767E435Responses = {
  /**
   * Danh sách bài viết (phân trang)
   */
  200: {
    data?: Array<Post>;
    links?: PaginationLinks;
    meta?: PaginationMeta;
  };
};

export type Fda362E2E082B5357Ac416E7767E435Response =
  Fda362E2E082B5357Ac416E7767E435Responses[keyof Fda362E2E082B5357Ac416E7767E435Responses];

export type Dcb66200C3132996151884Ac232Cf439Data = {
  body: PostRequest;
  path?: never;
  query?: never;
  url: "/api/posts";
};

export type Dcb66200C3132996151884Ac232Cf439Errors = {
  /**
   * Lỗi xác thực dữ liệu (Validation Error)
   */
  422: {
    message?: string;
    errors?: {
      title?: Array<string>;
      category_id?: Array<string>;
    };
  };
  /**
   * Lỗi server nội bộ
   */
  500: unknown;
};

export type Dcb66200C3132996151884Ac232Cf439Error =
  Dcb66200C3132996151884Ac232Cf439Errors[keyof Dcb66200C3132996151884Ac232Cf439Errors];

export type Dcb66200C3132996151884Ac232Cf439Responses = {
  /**
   * Tạo bài viết thành công
   */
  201: Post;
};

export type Dcb66200C3132996151884Ac232Cf439Response =
  Dcb66200C3132996151884Ac232Cf439Responses[keyof Dcb66200C3132996151884Ac232Cf439Responses];

export type D99F2E42Af2F722A058A86245Aa856fData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/posts/{id}";
};

export type D99F2E42Af2F722A058A86245Aa856fResponses = {
  /**
   * Xoá thành công
   */
  204: void;
};

export type D99F2E42Af2F722A058A86245Aa856fResponse =
  D99F2E42Af2F722A058A86245Aa856fResponses[keyof D99F2E42Af2F722A058A86245Aa856fResponses];

export type B5Adb0520Cca80Cedfe09D9298332Data = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/posts/{id}";
};

export type B5Adb0520Cca80Cedfe09D9298332Errors = {
  /**
   * Không tìm thấy bài viết
   */
  404: {
    message?: string;
  };
};

export type B5Adb0520Cca80Cedfe09D9298332Error =
  B5Adb0520Cca80Cedfe09D9298332Errors[keyof B5Adb0520Cca80Cedfe09D9298332Errors];

export type B5Adb0520Cca80Cedfe09D9298332Responses = {
  /**
   * Chi tiết bài viết
   */
  200: Post;
};

export type B5Adb0520Cca80Cedfe09D9298332Response =
  B5Adb0520Cca80Cedfe09D9298332Responses[keyof B5Adb0520Cca80Cedfe09D9298332Responses];

export type F4Bed0846D9350903D8A17C7B503aData = {
  body: PostRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/posts/{id}";
};

export type F4Bed0846D9350903D8A17C7B503aResponses = {
  /**
   * Cập nhật thành công
   */
  200: unknown;
};
